# -*- coding: utf-8 -*-
"""groq版

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5IMouaW4-dIimunctAuhBXdAUkjR--h

app.py
"""

import streamlit as st
import json
from groq import Groq

# 頁面設定
st.set_page_config(page_title="附中 AI 導覽員")
st.title("陽明交大附中 - 小北導覽")

# 讀取背景知識
try:
    with open('tour.json', 'r', encoding='utf-8') as f:
        context_data = json.load(f)
        context_text = json.dumps(context_data, ensure_ascii=False)
except FileNotFoundError:
    st.error("找不到 tour.json 檔案")
    st.stop()
except Exception as e:
    st.error(f"讀取 JSON 發生錯誤：{e}")
    st.stop()

# 系統人設指令
system_instruction = (
    f"你是陽明交大附中導覽員「小北」。\n"
    f"請優先參考以下內容回答。\n\n"
    f"內容：\n{context_text}"
)

# 初始化 API 與對話
if "groq_client" not in st.session_state:
    try:
        api_key = st.secrets["GROQ_API_KEY"]
    except KeyError:
        st.error("未找到 GROQ_API_KEY")
        st.stop()

    # 建立 Groq 客戶端
    client = Groq(api_key=api_key)
    st.session_state.groq_client = client

    st.session_state.messages = [
        {"role": "assistant", "content": "你好，我是導覽員小北，請隨時發問。"}
    ]

# 顯示歷史紀錄
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])

# 處理使用者輸入
if prompt := st.chat_input("想問什麼事"):
    st.chat_message("user").write(prompt)

    # 將使用者訊息加入歷史紀錄清單中
    st.session_state.messages.append({"role": "user", "content": prompt})

    with st.spinner("處理中"):
        try:
            # 將系統人設與歷史紀錄合併，準備傳給 Groq
            api_messages = [{"role": "system", "content": system_instruction}] + st.session_state.messages

            # 呼叫 Groq API
            response = st.session_state.groq_client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=api_messages,
                temperature=0.7
            )

            # 取得模型回應文字
            response_text = response.choices[0].message.content

            st.chat_message("assistant").write(response_text)
            st.session_state.messages.append({"role": "assistant", "content": response_text})

        except Exception as e:
            st.error(f"對話發生異常：{e}")

"""requirements.txt 內容設定"""

streamlit
groq

"""tour.json 檔案內容概覽"""

{
  "特色班級": {
    "生物醫學實驗班": "與陽明交大醫學院合作，學習智慧醫療與生命科學。",
    "電機資訊實驗班": "結合 AI 與半導體課程，培育未來的護國群山科技人才。",
    "雙語實驗班": "2021年成立，是竹苗地區首間成立雙語實驗專班的國立高中。"
  },
  "校歌內容": {
    "作曲": "駱正榮先生",
    "作詞": "連添財先生",
    "歌詞": "豆子埔溪畔，可愛的校園，成長的搖籃；精誠博雅，紳士淑女的風範，為人處事的領綱。豆子埔溪畔，快樂的校園，三年的同窗；開闊胸襟，是我竹北的夥伴，是我學習的榜樣。溪畔搖籃令我回憶，溪畔搖籃令我難忘。"
  }
}